// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwLrfxM7n-QjInpe2m7AJnFpTW8OvXFhE',
    appId: '1:253837486153:web:9a86c36e2af195ed44b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    authDomain: 'pataslk-app.firebaseapp.com',
    storageBucket: 'pataslk-app.firebasestorage.app',
    measurementId: 'G-F995B1M83R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-4msJp_Ssp238uPOwjWLtN-ls-SJp0U',
    appId: '1:253837486153:android:9573afe7a3139eeb44b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    storageBucket: 'pataslk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczPJCWLezLOcTRLFAj2ih4UzfxQBGtqY',
    appId: '1:253837486153:ios:dfd145e89dca845b44b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    storageBucket: 'pataslk-app.firebasestorage.app',
    androidClientId: '253837486153-61gpnpmujlr4f4k7hdcq06rdnh24lr7l.apps.googleusercontent.com',
    iosClientId: '253837486153-38crld2nhq6h5trg8spqrcgbj2gj1u13.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCczPJCWLezLOcTRLFAj2ih4UzfxQBGtqY',
    appId: '1:253837486153:ios:dfd145e89dca845b44b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    storageBucket: 'pataslk-app.firebasestorage.app',
    androidClientId: '253837486153-61gpnpmujlr4f4k7hdcq06rdnh24lr7l.apps.googleusercontent.com',
    iosClientId: '253837486153-38crld2nhq6h5trg8spqrcgbj2gj1u13.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwLrfxM7n-QjInpe2m7AJnFpTW8OvXFhE',
    appId: '1:253837486153:web:dd1d83d1c2c1f69b44b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    authDomain: 'pataslk-app.firebaseapp.com',
    storageBucket: 'pataslk-app.firebasestorage.app',
    measurementId: 'G-NG4E27BLVR',
  );
}
